// API Configuration
export const API_CONFIG = {
  baseUrl: import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000',
  timeout: 30000,
};

// API Endpoints
export const API_ENDPOINTS = {
  auth: {
    login: '/api/auth/login',
    changePassword: '/api/auth/change-password',
    resetPassword: '/api/auth/reset-password',
  },
  users: {
    list: '/api/users',
    get: (id: string) => `/api/users/${id}`,
    create: '/api/users',
    update: (id: string) => `/api/users/${id}`,
    delete: (id: string) => `/api/users/${id}`,
    restore: (id: string) => `/api/users/${id}/restore`,
    team: (userId: string) => `/api/users/team/${userId}`,
  },
  tasks: {
    list: '/api/tasks',
    get: (id: string) => `/api/tasks/${id}`,
    create: '/api/tasks',
    update: (id: string) => `/api/tasks/${id}`,
    delete: (id: string) => `/api/tasks/${id}`,
    updateStatus: (id: string) => `/api/tasks/${id}/status`,
    updateRoleStatus: (id: string) => `/api/tasks/${id}/role-status`,
    completeAll: (id: string) => `/api/tasks/${id}/complete-all`,
    retrieve: (id: string) => `/api/tasks/${id}/retrieve`,
    personal: (userId: string) => `/api/tasks/personal/${userId}`,
    travel: (userId: string) => `/api/tasks/travel/${userId}`,
    meeting: (userId: string) => `/api/tasks/meeting/${userId}`,
    isLongRunning: (id: string) => `/api/tasks/${id}/is-long-running`,
    batch: '/api/tasks/batch',
  },
  projects: {
    list: '/api/projects',
    get: (id: string) => `/api/projects/${id}`,
    create: '/api/projects',
    update: (id: string) => `/api/projects/${id}`,
    delete: (id: string) => `/api/projects/${id}`,
    statistics: '/api/projects/statistics',
    inUse: (id: string) => `/api/projects/${id}/in-use`,
  },
  taskClasses: {
    list: '/api/TaskClasses',
    get: (id: string) => `/api/TaskClasses/${id}`,
    create: '/api/TaskClasses',
    update: (id: string) => `/api/TaskClasses/${id}`,
    delete: (id: string) => `/api/TaskClasses/${id}`,
  },
  taskPool: {
    list: '/api/taskpool',
    get: (id: string) => `/api/taskpool/${id}`,
    create: '/api/taskpool',
    update: (id: string) => `/api/taskpool/${id}`,
    delete: (id: string) => `/api/taskpool/${id}`,
    assign: (id: string) => `/api/taskpool/${id}/assign`,
    statistics: '/api/taskpool/statistics',
    batchAssign: '/api/taskpool/batch-assign',
    duplicate: (id: string) => `/api/taskpool/${id}/duplicate`,
    retrieveFromTask: (taskId: string) => `/api/taskpool/retrieve/${taskId}`,
  },
  statistics: {
    dashboard: '/api/statistics/dashboard',
    personal: (userId: string) => `/api/statistics/personal?userId=${userId}`,
    personalTasks: (userId: string) => `/api/statistics/personal/tasks?userId=${userId}`,
    team: '/api/statistics/team',
    workload: '/api/statistics/workload',
    monthlyTrend: '/api/statistics/trend/monthly',
    dailyTrend: '/api/statistics/trend/daily',
    delayed: '/api/statistics/delayed',
    overdue: '/api/statistics/overdue',
    travel: '/api/statistics/travel',
    meeting: '/api/statistics/meeting',
    workdays: '/api/statistics/workdays',
  },
  settings: {
    equipmentModels: '/api/settings/equipment-models',
    capacityLevels: '/api/settings/capacity-levels',
    travelLabels: '/api/settings/travel-labels',
    taskCategories: '/api/settings/task-categories',
  },
};
