// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManageSystem.Infrastructure.Data;

#nullable disable

namespace TaskManageSystem.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260124000000_UpdateTaskFields")]
    partial class UpdateTaskFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TaskManageSystem.Domain.Entities.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Id");

                    b.Property<string>("Capacity")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Capacity")
                        .UseCollation("utf8mb4");

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasColumnName("Category");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("EndDate");

                    b.Property<bool>("IsCommissioned")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsCommissioned");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsCompleted");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsForeign")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsForeign");

                    b.Property<bool>("IsKeyProject")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsKeyProject");

                    b.Property<bool>("IsWon")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsWon");

                    b.Property<string>("Model")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Model")
                        .UseCollation("utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Name")
                        .UseCollation("utf8mb4");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext")
                        .HasColumnName("Remark")
                        .UseCollation("utf8mb4");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("StartDate");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("WorkNo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("WorkNo")
                        .UseCollation("utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("projects", "utf8mb4");
                });

            modelBuilder.Entity("TaskManageSystem.Domain.Entities.TaskClass", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Description")
                        .UseCollation("utf8mb4");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name")
                        .UseCollation("utf8mb4");

                    b.Property<string>("Notice")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Notice")
                        .UseCollation("utf8mb4");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("task_classes", "utf8mb4");
                });

            modelBuilder.Entity("TaskManageSystem.Domain.Entities.TaskItem", b =>
                {
                    b.Property<string>("TaskID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TaskID");

                    b.Property<string>("ApproverID")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ApproverID")
                        .UseCollation("utf8mb4");

                    b.Property<string>("ApproverName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ApproverName")
                        .UseCollation("utf8mb4");

                    b.Property<decimal?>("ApproverWorkload")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("ApproverWorkload");

                    b.Property<int?>("ApproverStatus")
                        .HasColumnType("int")
                        .HasColumnName("ApproverStatus");

                    b.Property<string>("AssigneeID")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("AssigneeID")
                        .UseCollation("utf8mb4");

                    b.Property<string>("AssigneeName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("AssigneeName")
                        .UseCollation("utf8mb4");

                    b.Property<int?>("AssigneeStatus")
                        .HasColumnType("int")
                        .HasColumnName("AssigneeStatus");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Category")
                        .UseCollation("utf8mb4");

                    b.Property<string>("CheckerID")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CheckerID")
                        .UseCollation("utf8mb4");

                    b.Property<string>("CheckerName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CheckerName")
                        .UseCollation("utf8mb4");

                    b.Property<decimal?>("CheckerWorkload")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("CheckerWorkload");

                    b.Property<int?>("CheckerStatus")
                        .HasColumnType("int")
                        .HasColumnName("CheckerStatus");

                    b.Property<string>("ChiefDesignerID")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ChiefDesignerID")
                        .UseCollation("utf8mb4");

                    b.Property<string>("ChiefDesignerName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ChiefDesignerName")
                        .UseCollation("utf8mb4");

                    b.Property<decimal?>("ChiefDesignerWorkload")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("ChiefDesignerWorkload");

                    b.Property<int?>("ChiefDesignerStatus")
                        .HasColumnType("int")
                        .HasColumnName("ChiefDesignerStatus");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CompletedDate");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CreatedBy")
                        .UseCollation("utf8mb4");

                    b.Property<decimal?>("Difficulty")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("Difficulty");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime")
                        .HasColumnName("DueDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsForceAssessment")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsForceAssessment");

                    b.Property<bool>("IsIndependentBusinessUnit")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsIndependentBusinessUnit");

                    b.Property<bool>("IsInPool")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsInPool");

                    b.Property<decimal?>("MeetingDuration")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("MeetingDuration");

                    b.Property<string>("ParticipantNames")
                        .HasColumnType("longtext")
                        .HasColumnName("ParticipantNames")
                        .UseCollation("utf8mb4");

                    b.Property<string>("Participants")
                        .HasColumnType("longtext")
                        .HasColumnName("Participants")
                        .UseCollation("utf8mb4");

                    b.Property<string>("ProjectID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ProjectID");

                    b.Property<string>("RelatedProject")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("RelatedProject")
                        .UseCollation("utf8mb4");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext")
                        .HasColumnName("Remark")
                        .UseCollation("utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("StartDate");

                    b.Property<string>("TaskClassID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TaskClassID");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("TaskName")
                        .UseCollation("utf8mb4");

                    b.Property<decimal?>("TravelDuration")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("TravelDuration");

                    b.Property<string>("TravelLabel")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TravelLabel")
                        .UseCollation("utf8mb4");

                    b.Property<string>("TravelLocation")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("TravelLocation")
                        .UseCollation("utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UserID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UserID");

                    b.Property<string>("UserID1")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UserID1");

                    b.Property<string>("UserID2")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UserID2");

                    b.Property<string>("UserID3")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UserID3");

                    b.Property<string>("UserID4")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UserID4");

                    b.Property<decimal?>("Workload")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Workload");

                    b.HasKey("TaskID")
                        .HasName("PRIMARY");

                    b.ToTable("tasks", "utf8mb4");
                });

            modelBuilder.Entity("TaskManageSystem.Domain.Entities.TaskPoolItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Id");

                    b.Property<string>("ApproverID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ApproverID");

                    b.Property<string>("ApproverName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ApproverName")
                        .UseCollation("utf8mb4");

                    b.Property<decimal?>("ApproverWorkload")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("ApproverWorkload");

                    b.Property<int?>("ApproverStatus")
                        .HasColumnType("int")
                        .HasColumnName("ApproverStatus");

                    b.Property<string>("AssigneeID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("AssigneeID");

                    b.Property<string>("AssigneeName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("AssigneeName")
                        .UseCollation("utf8mb4");

                    b.Property<int?>("AssigneeStatus")
                        .HasColumnType("int")
                        .HasColumnName("AssigneeStatus");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Category")
                        .UseCollation("utf8mb4");

                    b.Property<string>("CheckerID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CheckerID");

                    b.Property<string>("CheckerName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CheckerName")
                        .UseCollation("utf8mb4");

                    b.Property<decimal?>("CheckerWorkload")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("CheckerWorkload");

                    b.Property<int?>("CheckerStatus")
                        .HasColumnType("int")
                        .HasColumnName("CheckerStatus");

                    b.Property<string>("ChiefDesignerID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ChiefDesignerID");

                    b.Property<string>("ChiefDesignerName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ChiefDesignerName")
                        .UseCollation("utf8mb4");

                    b.Property<decimal?>("ChiefDesignerWorkload")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("ChiefDesignerWorkload");

                    b.Property<int?>("ChiefDesignerStatus")
                        .HasColumnType("int")
                        .HasColumnName("ChiefDesignerStatus");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CompletedDate");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CreatedBy")
                        .UseCollation("utf8mb4");

                    b.Property<decimal?>("Difficulty")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("Difficulty");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime")
                        .HasColumnName("DueDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsForceAssessment")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsForceAssessment");

                    b.Property<bool>("IsInPool")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsInPool");

                    b.Property<decimal?>("MeetingDuration")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("MeetingDuration");

                    b.Property<string>("ParticipantNames")
                        .HasColumnType("longtext")
                        .HasColumnName("ParticipantNames")
                        .UseCollation("utf8mb4");

                    b.Property<string>("Participants")
                        .HasColumnType("longtext")
                        .HasColumnName("Participants")
                        .UseCollation("utf8mb4");

                    b.Property<string>("PersonInChargeID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PersonInChargeID");

                    b.Property<string>("PersonInChargeName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PersonInChargeName")
                        .UseCollation("utf8mb4");

                    b.Property<string>("ProjectID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ProjectID");

                    b.Property<int>("ReviewerID2")
                        .HasColumnType("int")
                        .HasColumnName("ReviewerID2");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext")
                        .HasColumnName("Remark")
                        .UseCollation("utf8mb4");

                    b.Property<int>("ReviewerID")
                        .HasColumnType("int")
                        .HasColumnName("ReviewerID");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("StartDate");

                    b.Property<string>("TaskClassID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TaskClassID");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("TaskName")
                        .UseCollation("utf8mb4");

                    b.Property<decimal?>("TravelDuration")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("TravelDuration");

                    b.Property<string>("TravelLabel")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TravelLabel")
                        .UseCollation("utf8mb4");

                    b.Property<string>("TravelLocation")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("TravelLocation")
                        .UseCollation("utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdatedAt");

                    b.Property<decimal?>("Workload")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Workload");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("task_pool", "utf8mb4");
                });

            modelBuilder.Entity("TaskManageSystem.Domain.Entities.User", b =>
                {
                    b.Property<string>("UserID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UserID");

                    b.Property<string>("Education")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Education")
                        .UseCollation("utf8mb4");

                    b.Property<DateTime?>("JoinDate")
                        .HasColumnType("datetime")
                        .HasColumnName("JoinDate");

                    b.Property<int>("OfficeLocation")
                        .HasColumnType("int")
                        .HasColumnName("OfficeLocation");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PasswordHash")
                        .UseCollation("utf8mb4");

                    b.Property<string>("Remark")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Remark")
                        .UseCollation("utf8mb4");

                    b.Property<string>("School")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("School")
                        .UseCollation("utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<int>("SystemRole")
                        .HasColumnType("int")
                        .HasColumnName("SystemRole");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Title")
                        .UseCollation("utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name")
                        .UseCollation("utf8mb4");

                    b.HasKey("UserID")
                        .HasName("PRIMARY");

                    b.ToTable("users", "utf8mb4");
                });
#pragma warning restore 612, 618
        }
    }
}
