// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManageSystem.Infrastructure.Data;

#nullable disable

namespace TaskManageSystem.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TaskManageSystem.Domain.Entities.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Capacity")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCommissioned")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsForeign")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsKeyProject")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsWon")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Remark")
                        .HasColumnType("LONGTEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WorkNo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("StartDate");

                    b.ToTable("projects", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                });

            modelBuilder.Entity("TaskManageSystem.Domain.Entities.SystemConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConfigCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigCategory")
                        .HasDatabaseName("IX_SystemConfigs_Category");

                    b.HasIndex("ConfigCategory", "ConfigKey")
                        .IsUnique()
                        .HasDatabaseName("IX_SystemConfigs_Category_Key");

                    b.ToTable("SystemConfigs", (string)null);
                });

            modelBuilder.Entity("TaskManageSystem.Domain.Entities.TaskClass", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Notice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("task_classes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "TC001",
                            Code = 0,
                            CreatedAt = new DateTime(2026, 1, 24, 2, 39, 49, 880, DateTimeKind.Utc).AddTicks(2095),
                            Description = "市场配合相关任务",
                            IsDeleted = false,
                            Name = "市场配合"
                        },
                        new
                        {
                            Id = "TC002",
                            Code = 1,
                            CreatedAt = new DateTime(2026, 1, 24, 2, 39, 49, 880, DateTimeKind.Utc).AddTicks(2099),
                            Description = "常规项目执行相关任务",
                            IsDeleted = false,
                            Name = "常规项目执行"
                        },
                        new
                        {
                            Id = "TC003",
                            Code = 2,
                            CreatedAt = new DateTime(2026, 1, 24, 2, 39, 49, 880, DateTimeKind.Utc).AddTicks(2100),
                            Description = "核电项目执行相关任务",
                            IsDeleted = false,
                            Name = "核电项目执行"
                        },
                        new
                        {
                            Id = "TC004",
                            Code = 3,
                            CreatedAt = new DateTime(2026, 1, 24, 2, 39, 49, 880, DateTimeKind.Utc).AddTicks(2101),
                            Description = "产品研发相关任务",
                            IsDeleted = false,
                            Name = "产品研发"
                        },
                        new
                        {
                            Id = "TC005",
                            Code = 4,
                            CreatedAt = new DateTime(2026, 1, 24, 2, 39, 49, 880, DateTimeKind.Utc).AddTicks(2102),
                            Description = "科研项目相关任务",
                            IsDeleted = false,
                            Name = "科研任务"
                        },
                        new
                        {
                            Id = "TC006",
                            Code = 5,
                            CreatedAt = new DateTime(2026, 1, 24, 2, 39, 49, 880, DateTimeKind.Utc).AddTicks(2103),
                            Description = "改造服务相关任务",
                            IsDeleted = false,
                            Name = "改造服务"
                        },
                        new
                        {
                            Id = "TC007",
                            Code = 6,
                            CreatedAt = new DateTime(2026, 1, 24, 2, 39, 49, 880, DateTimeKind.Utc).AddTicks(2104),
                            Description = "会议和培训任务",
                            IsDeleted = false,
                            Name = "内部会议与培训"
                        },
                        new
                        {
                            Id = "TC008",
                            Code = 7,
                            CreatedAt = new DateTime(2026, 1, 24, 2, 39, 49, 880, DateTimeKind.Utc).AddTicks(2105),
                            Description = "行政和党建任务",
                            IsDeleted = false,
                            Name = "行政与党建"
                        },
                        new
                        {
                            Id = "TC009",
                            Code = 8,
                            CreatedAt = new DateTime(2026, 1, 24, 2, 39, 49, 880, DateTimeKind.Utc).AddTicks(2106),
                            Description = "出差任务",
                            IsDeleted = false,
                            Name = "差旅任务"
                        },
                        new
                        {
                            Id = "TC010",
                            Code = 9,
                            CreatedAt = new DateTime(2026, 1, 24, 2, 39, 49, 880, DateTimeKind.Utc).AddTicks(2106),
                            Description = "其他类型任务",
                            IsDeleted = false,
                            Name = "其他任务"
                        });
                });

            modelBuilder.Entity("TaskManageSystem.Domain.Entities.TaskItem", b =>
                {
                    b.Property<string>("TaskID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ApproverID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ApproverName")
                        .HasColumnType("longtext");

                    b.Property<int?>("ApproverStatus")
                        .HasColumnType("int");

                    b.Property<decimal?>("ApproverWorkload")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("AssigneeID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AssigneeName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("AssigneeStatus")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CheckerID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CheckerName")
                        .HasColumnType("longtext");

                    b.Property<int?>("CheckerStatus")
                        .HasColumnType("int");

                    b.Property<decimal?>("CheckerWorkload")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ChiefDesignerID")
                        .HasColumnType("longtext");

                    b.Property<string>("ChiefDesignerName")
                        .HasColumnType("longtext");

                    b.Property<int?>("ChiefDesignerStatus")
                        .HasColumnType("int");

                    b.Property<decimal?>("ChiefDesignerWorkload")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Difficulty")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsForceAssessment")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsInPool")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsIndependentBusinessUnit")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("MeetingDuration")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ParticipantNames")
                        .HasColumnType("LONGTEXT");

                    b.Property<string>("Participants")
                        .HasColumnType("LONGTEXT");

                    b.Property<string>("ProjectID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RelatedProject")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Remark")
                        .HasColumnType("LONGTEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TaskClassID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal?>("TravelDuration")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TravelLabel")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TravelLocation")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Workload")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("TaskID");

                    b.HasIndex("ApproverID");

                    b.HasIndex("AssigneeID");

                    b.HasIndex("CheckerID");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("ProjectID");

                    b.HasIndex("Status");

                    b.HasIndex("TaskClassID");

                    b.ToTable("tasks", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                });

            modelBuilder.Entity("TaskManageSystem.Domain.Entities.TaskPoolItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ApproverID")
                        .HasColumnType("longtext");

                    b.Property<string>("ApproverName")
                        .HasColumnType("longtext");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CheckerID")
                        .HasColumnType("longtext");

                    b.Property<string>("CheckerName")
                        .HasColumnType("longtext");

                    b.Property<string>("ChiefDesignerID")
                        .HasColumnType("longtext");

                    b.Property<string>("ChiefDesignerName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsForceAssessment")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PersonInChargeID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PersonInChargeName")
                        .HasColumnType("longtext");

                    b.Property<string>("ProjectID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Remark")
                        .HasColumnType("LONGTEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TaskClassID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("PersonInChargeID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("TaskClassID");

                    b.ToTable("task_pool", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                });

            modelBuilder.Entity("TaskManageSystem.Domain.Entities.User", b =>
                {
                    b.Property<string>("UserID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Education")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("JoinDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("OfficeLocation")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Remark")
                        .HasColumnType("LONGTEXT");

                    b.Property<string>("School")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SystemRole")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserID");

                    b.HasIndex("OfficeLocation");

                    b.HasIndex("Status");

                    b.HasIndex("SystemRole");

                    b.ToTable("users", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");

                    b.HasData(
                        new
                        {
                            UserID = "admin",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "系统管理员",
                            OfficeLocation = 0,
                            PasswordHash = "$2a$11$FAMHDGXReJhStFAfXZKODOZxfWK.d3QYVU4xL02rnIikDP.5ZTggu",
                            Status = 0,
                            SystemRole = 2
                        },
                        new
                        {
                            UserID = "LEADER001",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            JoinDate = new DateTime(2015, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "张组长",
                            OfficeLocation = 1,
                            PasswordHash = "$2a$11$GyTZWGAt.JGm3Dp3jf3keOxXLseZE3rc5MOdA029t2AEc3aIgnW7y",
                            Status = 0,
                            SystemRole = 1,
                            Title = "主任工程师"
                        },
                        new
                        {
                            UserID = "USER001",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "硕士",
                            IsDeleted = false,
                            JoinDate = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "李研究员",
                            OfficeLocation = 0,
                            PasswordHash = "$2a$11$kkpSrXh4cDiXqAGRFrbYT.mESnXOKWw.2.68ObojrWnuYxUq6SVyu",
                            School = "四川大学",
                            Status = 0,
                            SystemRole = 0,
                            Title = "工程师"
                        });
                });

            modelBuilder.Entity("TaskManageSystem.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("TaskManageSystem.Domain.Entities.Project", null)
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectID");

                    b.HasOne("TaskManageSystem.Domain.Entities.TaskClass", null)
                        .WithMany("Tasks")
                        .HasForeignKey("TaskClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskManageSystem.Domain.Entities.TaskPoolItem", b =>
                {
                    b.HasOne("TaskManageSystem.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskManageSystem.Domain.Entities.User", "PersonInCharge")
                        .WithMany()
                        .HasForeignKey("PersonInChargeID");

                    b.HasOne("TaskManageSystem.Domain.Entities.Project", "Project")
                        .WithMany("PoolItems")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TaskManageSystem.Domain.Entities.TaskClass", "TaskClass")
                        .WithMany()
                        .HasForeignKey("TaskClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("PersonInCharge");

                    b.Navigation("Project");

                    b.Navigation("TaskClass");
                });

            modelBuilder.Entity("TaskManageSystem.Domain.Entities.Project", b =>
                {
                    b.Navigation("PoolItems");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskManageSystem.Domain.Entities.TaskClass", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
